// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQxXnnWLtOUvSJsAINPB-NhvB2rtLjP18',
    appId: '1:702651377428:web:d48393ee8f7f3ac5088401',
    messagingSenderId: '702651377428',
    projectId: 'espritalumni',
    authDomain: 'espritalumni.firebaseapp.com',
    storageBucket: 'espritalumni.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlrp-fm9LOqoC8Y3Td2sDXF-Ln_LSiy-I',
    appId: '1:702651377428:android:cda991d5e0a8dff8088401',
    messagingSenderId: '702651377428',
    projectId: 'espritalumni',
    storageBucket: 'espritalumni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHn_tDc9hWk9LpfB-dTd-88-qQzkzAa5U',
    appId: '1:702651377428:ios:2b724f507b3aa698088401',
    messagingSenderId: '702651377428',
    projectId: 'espritalumni',
    storageBucket: 'espritalumni.appspot.com',
    iosClientId: '702651377428-gahojnahi6879lpqgv72sbh1q98m2kfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.espritAlumniFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHn_tDc9hWk9LpfB-dTd-88-qQzkzAa5U',
    appId: '1:702651377428:ios:2b724f507b3aa698088401',
    messagingSenderId: '702651377428',
    projectId: 'espritalumni',
    storageBucket: 'espritalumni.appspot.com',
    iosClientId: '702651377428-gahojnahi6879lpqgv72sbh1q98m2kfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.espritAlumniFrontend',
  );
}
